---
functional:
  - Пользователь должен иметь возможность регистрироваться на сайте
  - Пользователь должен иметь возможность создавать игру с различными опциями (бот или человек, сложность игры, |
    выбор задачи)
  - Пользователь должен иметь возможность выбирать язык программирования
  - Пользователь должен иметь возможность видеть код соперника (бота или другого пользователя)
  - При правильном решении задачи быстрее соперника, пользователь должен иметь возможность видеть |
    положительный результат соревнования
  - При неправильном решении задачи пользователь должен иметь возможность видеть уведомление об |
    отрицательном результате решения
  - При решении задачи медленнее соперника, пользователь должен иметь возможность видеть отрицательный результат |
    соревнования
  - Пользователь должен иметь возможность просматривать информацию о своём профиле (рейтинг, статистика игр и т.д)
  - Пользователь должен иметь возможность просматривать общий рейтинг всех игроков
  - Пользователь должен иметь возможность просматривать историю игр, игры в записи
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
implicit:
  - У пользователя должен быть личный кабинет, в котором отображается статистика, рейтинг
